name: Build VoiceGPT
on:
  push:
    branches: [develop]
jobs:
  lint:
    name: Code linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install ESlint
        run: npm install eslint --global
      - name: Lint JS files
        run: eslint ./src/
  deploy:
    needs: lint
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Connect to remote server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Build and run
        run: |
          sudo chmod -R 777 /root;
          cd ${{ secrets.PROJECT_DIR }};
          git pull;
          docker rm voice-gpt-voice-gpt-1 -f;
          make;
