name: Test VoiceGPT
on:
  push:
    branches: [develop]
jobs:
  lint:
    name: Code linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install ESlint
        run: npm install eslint --global
      - name: Lint JS files
        run: eslint ./src/
